"""Generate cooperative-localization trajectory tubes and DCP quantile plots."""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass
from pathlib import Path

DEFAULT_MPLCONFIGDIR = Path(__file__).resolve().parent / "output" / ".mplconfig"
# Ensure Matplotlib cache/config writes to a local writable directory.
os.environ.setdefault("MPLCONFIGDIR", str(DEFAULT_MPLCONFIGDIR))

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

from collect_calibration_data import load_calibration_dataset
import sim_env
from agent_classes import AgentClass, normalize_agent_class
from heterogeneous_scenario import (
    default_class_quantiles,
    simulate_class_conditional_gs_ci_rollout,
)


plt.rcParams.update(
    {
        "font.size": 13,
        "axes.titlesize": 15,
        "axes.labelsize": 13,
        "legend.fontsize": 10,
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
    }
)


@dataclass(frozen=True)
class DCPDiagnostics:
    quantile_history: np.ndarray
    final_quantiles: np.ndarray
    local_quantiles: np.ndarray
    centralized_class_quantiles: dict[str, float]
    sample_counts: np.ndarray


def parse_args() -> argparse.Namespace:
    # CLI for rollout + DCP optimization + figure export.
    script_dir = Path(__file__).resolve().parent
    output_dir = script_dir / "output"

    parser = argparse.ArgumentParser(
        description=(
            "Plot cooperative-localization trajectories with baseline vs DCP-"
            "calibrated uncertainty tubes, and plot DCP quantiles over time."
        )
    )
    parser.add_argument("--steps", type=int, default=500, help="Number of localization timesteps.")
    parser.add_argument("--seed", type=int, default=7, help="Random seed for the rollout.")
    parser.add_argument(
        "--initial-jitter-std",
        type=float,
        default=0.25,
        help="Initial position jitter applied to the default team state.",
    )
    parser.add_argument("--dt", type=float, default=float(sim_env.dt), help="Scenario timestep in seconds.")
    parser.add_argument(
        "--observ-prob",
        type=float,
        default=float(sim_env.observ_prob),
        help="Observation-link probability used in the rollout.",
    )
    parser.add_argument(
        "--comm-prob",
        type=float,
        default=float(sim_env.comm_prob),
        help="Communication-link probability used in the rollout.",
    )
    parser.add_argument("--ci-coeff", type=float, default=0.8, help="Covariance-intersection convex coefficient.")
    parser.add_argument(
        "--calibration-dataset",
        type=Path,
        default=script_dir / "calibration_dataset.npz",
        help="Calibration dataset generated by collect_calibration_data.py (.npz, .pkl, .pickle, or .json).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=output_dir,
        help="Directory where the plots and metrics archive will be written.",
    )
    parser.add_argument(
        "--dcp-steps",
        type=int,
        default=250,
        help="Number of distributed subgradient iterations used for DCP.",
    )
    parser.add_argument(
        "--dcp-step-size",
        type=float,
        default=0.35,
        help="Initial DCP subgradient step size. The implementation uses 1/sqrt(k) decay.",
    )
    parser.add_argument(
        "--tube-alpha",
        type=float,
        default=0.18,
        help="Transparency of the uncertainty tubes.",
    )
    return parser.parse_args()


def configure_matplotlib(output_dir: Path) -> None:
    # Create deterministic writable config directory for headless plotting.
    mplconfig_dir = output_dir / ".mplconfig"
    mplconfig_dir.mkdir(parents=True, exist_ok=True)


def split_conformal_quantile(scores: np.ndarray, alpha: float) -> tuple[float, float]:
    # Compute split-conformal quantile level and the effective tau used.
    scores = np.asarray(scores, dtype=float)
    if scores.ndim != 1 or scores.size == 0:
        raise ValueError("scores must be a non-empty 1D array")
    if not (0.0 < alpha < 1.0):
        raise ValueError("alpha must be in (0, 1)")

    n = scores.size
    tau = float(np.ceil((n + 1) * (1.0 - alpha)) / n)
    tau = min(max(tau, 0.0), 1.0)
    return float(np.quantile(scores, tau, method="higher")), tau


def mahalanobis_radius(mean: np.ndarray, covariance: np.ndarray, truth: np.ndarray) -> float:
    # Convert posterior error into a scalar nonconformity score.
    mean = np.asarray(mean, dtype=float).reshape(-1)
    truth = np.asarray(truth, dtype=float).reshape(-1)
    covariance = np.asarray(covariance, dtype=float)
    covariance = 0.5 * (covariance + covariance.T)
    covariance += 1.0e-12 * np.eye(covariance.shape[0], dtype=float)
    diff = truth - mean
    inv_covariance = np.linalg.pinv(covariance)
    distance_sq = float(diff.T @ inv_covariance @ diff)
    return float(np.sqrt(max(distance_sq, 0.0)))


def load_dcp_calibration_scores(
    dataset_path: Path,
    agent_classes: list[str],
) -> tuple[dict[int, np.ndarray], dict[AgentClass, float]]:
    # Load class-partitioned offline samples and build per-agent score buffers.
    if not dataset_path.exists():
        raise FileNotFoundError(
            f"Calibration dataset not found at {dataset_path}. "
            "Run multirobot_localization/collect_calibration_data.py first."
        )

    dataset = load_calibration_dataset(dataset_path)

    scores_by_agent: dict[int, list[float]] = {agent_id: [] for agent_id in range(len(agent_classes))}
    scores_by_class: dict[AgentClass, list[float]] = {}
    alpha_by_class: dict[AgentClass, float] = {}

    # Score each sample with the corresponding local 2D block.
    for class_name, samples in dataset["samples_by_class"].items():
        agent_class = normalize_agent_class(class_name)
        scores_by_class.setdefault(agent_class, [])

        for sample in samples:
            agent_id = int(sample["agent_id"])
            truth_state = np.asarray(sample["ground_truth_state"], dtype=float).reshape(-1)
            posterior_mean = np.asarray(sample["posterior_mean"], dtype=float).reshape(-1)
            posterior_covariance = np.asarray(sample["posterior_covariance"], dtype=float)
            state_index = 2 * agent_id

            score = mahalanobis_radius(
                mean=posterior_mean[state_index:state_index + 2],
                covariance=posterior_covariance[state_index:state_index + 2, state_index:state_index + 2],
                truth=truth_state[state_index:state_index + 2],
            )
            scores_by_agent[agent_id].append(score)
            scores_by_class[agent_class].append(score)
            alpha_by_class[agent_class] = float(sample["epsilon"])

    # Fallback for sparse classes: borrow class pool if an agent has no direct samples.
    for agent_id, class_name in enumerate(agent_classes):
        agent_class = normalize_agent_class(class_name)
        if scores_by_agent[agent_id]:
            continue
        class_scores = scores_by_class.get(agent_class, [])
        if not class_scores:
            raise ValueError(f"No calibration scores found for agent {agent_id} ({agent_class.value})")
        scores_by_agent[agent_id] = list(class_scores)

    return (
        {agent_id: np.asarray(scores, dtype=float) for agent_id, scores in scores_by_agent.items()},
        alpha_by_class,
    )


def cycle_metropolis_weights(num_agents: int) -> np.ndarray:
    # Build doubly-stochastic mixing matrix for a cycle communication graph.
    if num_agents <= 0:
        raise ValueError("num_agents must be positive")
    if num_agents == 1:
        return np.ones((1, 1), dtype=float)

    adjacency = np.zeros((num_agents, num_agents), dtype=float)
    for agent_id in range(num_agents):
        adjacency[agent_id, (agent_id - 1) % num_agents] = 1.0
        adjacency[agent_id, (agent_id + 1) % num_agents] = 1.0

    degrees = adjacency.sum(axis=1)
    weights = np.zeros_like(adjacency)
    for i in range(num_agents):
        for j in range(num_agents):
            if i == j or adjacency[i, j] == 0.0:
                continue
            weights[i, j] = 1.0 / (1.0 + max(degrees[i], degrees[j]))
        weights[i, i] = 1.0 - weights[i].sum()
    return weights


def run_distributed_classwise_dcp(
    scores_by_agent: dict[int, np.ndarray],
    agent_classes: list[str],
    alpha_by_class: dict[AgentClass, float],
    num_steps: int,
    step_size: float,
) -> DCPDiagnostics:
    # Distributed subgradient routine run independently per class partition.
    num_agents = len(agent_classes)
    quantile_history = np.zeros((num_agents, num_steps + 1), dtype=float)
    local_quantiles = np.zeros(num_agents, dtype=float)
    final_quantiles = np.zeros(num_agents, dtype=float)
    sample_counts = np.zeros(num_agents, dtype=int)
    centralized_class_quantiles: dict[str, float] = {}

    # Initialize each agent from its local split-conformal quantile.
    for agent_id in range(num_agents):
        agent_class = normalize_agent_class(agent_classes[agent_id])
        local_scores = np.asarray(scores_by_agent[agent_id], dtype=float)
        local_quantiles[agent_id], _ = split_conformal_quantile(local_scores, alpha_by_class[agent_class])
        quantile_history[agent_id, 0] = local_quantiles[agent_id]
        sample_counts[agent_id] = int(local_scores.size)

    # Solve one class-specific DCP problem for each present class.
    unique_classes = [normalize_agent_class(agent_class) for agent_class in dict.fromkeys(agent_classes)]
    for agent_class in unique_classes:
        class_agent_ids = [
            agent_id
            for agent_id, class_name in enumerate(agent_classes)
            if normalize_agent_class(class_name) == agent_class
        ]
        class_scores = np.concatenate([scores_by_agent[agent_id] for agent_id in class_agent_ids], axis=0)
        _, tau = split_conformal_quantile(class_scores, alpha_by_class[agent_class])
        centralized_class_quantiles[agent_class.value] = split_conformal_quantile(
            class_scores,
            alpha_by_class[agent_class],
        )[0]

        current = quantile_history[class_agent_ids, 0].copy()
        mixing_weights = cycle_metropolis_weights(len(class_agent_ids))

        for step in range(1, num_steps + 1):
            # Consensus + subgradient correction with 1/sqrt(k) step decay.
            mixed_estimate = mixing_weights @ current
            step_scale = float(step_size) / np.sqrt(step)
            gradients = np.array(
                [
                    np.mean(scores_by_agent[agent_id] <= current[local_idx]) - tau
                    for local_idx, agent_id in enumerate(class_agent_ids)
                ],
                dtype=float,
            )
            current = np.maximum(mixed_estimate - step_scale * gradients, 1.0e-6)
            quantile_history[class_agent_ids, step] = current

        final_quantiles[class_agent_ids] = current

    return DCPDiagnostics(
        quantile_history=quantile_history,
        final_quantiles=final_quantiles,
        local_quantiles=local_quantiles,
        centralized_class_quantiles=centralized_class_quantiles,
        sample_counts=sample_counts,
    )


def tangent_normals(points: np.ndarray) -> np.ndarray:
    # Estimate per-point curve normals from finite-difference tangents.
    tangents = np.zeros_like(points)
    if points.shape[0] == 1:
        tangents[0] = np.array([1.0, 0.0])
    else:
        tangents[0] = points[1] - points[0]
        tangents[-1] = points[-1] - points[-2]
        if points.shape[0] > 2:
            tangents[1:-1] = points[2:] - points[:-2]

    tangent_norm = np.linalg.norm(tangents, axis=1, keepdims=True)
    tangent_norm = np.where(tangent_norm < 1.0e-9, 1.0, tangent_norm)
    unit_tangent = tangents / tangent_norm
    normals = np.column_stack((-unit_tangent[:, 1], unit_tangent[:, 0]))
    return normals


def covariance_tube_radius(
    covariances: np.ndarray,
    normals: np.ndarray,
    scale: float,
) -> np.ndarray:
    # Project covariance along local normal direction to get tube half-width.
    variances = np.einsum("ti,tij,tj->t", normals, covariances, normals)
    variances = np.maximum(variances, 0.0)
    return float(scale) * np.sqrt(variances)


def draw_uncertainty_tube(
    ax,
    estimated_positions: np.ndarray,
    covariances: np.ndarray,
    scale: float,
    color,
    alpha: float,
) -> None:
    # Draw a closed polygon around the estimated trajectory centerline.
    normals = tangent_normals(estimated_positions)
    radius = covariance_tube_radius(covariances, normals, scale=scale)
    upper = estimated_positions + normals * radius[:, None]
    lower = estimated_positions - normals * radius[:, None]
    polygon = np.vstack((upper, lower[::-1]))
    ax.fill(polygon[:, 0], polygon[:, 1], color=color, alpha=alpha, linewidth=0.0)


def save_top_down_uncertainty_plot(
    rollout: dict[str, object],
    dcp: DCPDiagnostics,
    output_path: Path,
    tube_alpha: float,
) -> None:
    # Side-by-side figure: raw covariance tubes vs DCP-calibrated tubes.
    truth_positions = np.asarray(rollout["truth_positions"], dtype=float)
    estimated_positions = np.asarray(rollout["estimated_positions"], dtype=float)
    raw_covariances = np.asarray(rollout["raw_covariances"], dtype=float)
    agent_classes = list(rollout["agent_classes"])

    num_agents = truth_positions.shape[0]
    colors = plt.get_cmap("tab10")(np.arange(num_agents) % 10)

    fig, axes = plt.subplots(1, 2, figsize=(15, 7), sharex=True, sharey=True)
    subplot_specs = [
        ("Baseline Covariance", np.ones(num_agents, dtype=float)),
        ("DCP-Calibrated Covariance", dcp.final_quantiles),
    ]

    for ax, (title, scales) in zip(axes, subplot_specs):
        # Draw one uncertainty tube + true/estimated trajectories per agent.
        for agent_id in range(num_agents):
            color = colors[agent_id]
            truth_xy = truth_positions[agent_id]
            estimate_xy = estimated_positions[agent_id]
            draw_uncertainty_tube(
                ax=ax,
                estimated_positions=estimate_xy,
                covariances=raw_covariances[agent_id],
                scale=float(scales[agent_id]),
                color=color,
                alpha=tube_alpha,
            )
            ax.plot(truth_xy[:, 0], truth_xy[:, 1], color=color, linewidth=2.2)
            ax.plot(estimate_xy[:, 0], estimate_xy[:, 1], color=color, linewidth=1.7, linestyle="--")
            ax.scatter(truth_xy[0, 0], truth_xy[0, 1], color=color, s=18, zorder=5)
            ax.text(
                estimate_xy[-1, 0],
                estimate_xy[-1, 1],
                f"A{agent_id}",
                color=color,
                fontsize=9,
                ha="left",
                va="bottom",
            )

        ax.set_title(title)
        ax.set_xlabel("x [m]")
        ax.set_ylabel("y [m]")
        ax.grid(alpha=0.25)
        ax.set_aspect("equal", adjustable="box")

    class_handles = [
        Line2D([0], [0], color=colors[agent_id], linewidth=2.2, label=f"A{agent_id} {normalize_agent_class(agent_classes[agent_id]).name.split('_')[-1]}")
        for agent_id in range(num_agents)
    ]
    style_handles = [
        Line2D([0], [0], color="black", linewidth=2.2, label="True trajectory"),
        Line2D([0], [0], color="black", linewidth=1.7, linestyle="--", label="Estimated trajectory"),
        Patch(facecolor=(0.5, 0.5, 0.5, tube_alpha), edgecolor="none", label="Uncertainty tube"),
    ]
    fig.legend(handles=style_handles + class_handles, loc="upper center", ncol=4, frameon=False)
    fig.suptitle("Cooperative Localization Trajectories with Baseline and DCP-Calibrated Tubes", y=0.98)
    fig.tight_layout(rect=(0.0, 0.0, 1.0, 0.90))
    fig.savefig(output_path, dpi=200, bbox_inches="tight")
    plt.close(fig)


def save_dcp_quantile_history_plot(
    dcp: DCPDiagnostics,
    agent_classes: list[str],
    output_path: Path,
) -> None:
    # Plot distributed per-agent quantile trajectories and centralized references.
    num_agents = len(agent_classes)
    colors = plt.get_cmap("tab10")(np.arange(num_agents) % 10)
    iterations = np.arange(dcp.quantile_history.shape[1], dtype=int)

    fig, ax = plt.subplots(figsize=(10.5, 5.8))
    for agent_id in range(num_agents):
        ax.plot(
            iterations,
            dcp.quantile_history[agent_id],
            color=colors[agent_id],
            linewidth=1.8,
            label=f"A{agent_id}",
        )

    for class_name, quantile in dcp.centralized_class_quantiles.items():
        agent_class = normalize_agent_class(class_name)
        linestyle = "--" if agent_class == AgentClass.CLASS_A_UGV else ":"
        ax.axhline(
            quantile,
            color=(0.2, 0.2, 0.2),
            linewidth=1.2,
            linestyle=linestyle,
            label=f"{agent_class.name.split('_')[-1]} centralized",
        )

    ax.set_title("DCP Quantiles Over Distributed Optimization Steps")
    ax.set_xlabel("DCP iteration")
    ax.set_ylabel("Quantile")
    ax.grid(alpha=0.25)
    ax.legend(ncol=3, frameon=False)
    fig.tight_layout()
    fig.savefig(output_path, dpi=200, bbox_inches="tight")
    plt.close(fig)


def save_metrics(
    output_path: Path,
    rollout: dict[str, object],
    dcp: DCPDiagnostics,
) -> None:
    # Persist arrays needed for downstream analysis without rerunning rollouts.
    np.savez(
        output_path,
        time=np.asarray(rollout["time"], dtype=float),
        truth_positions=np.asarray(rollout["truth_positions"], dtype=float),
        estimated_positions=np.asarray(rollout["estimated_positions"], dtype=float),
        raw_covariances=np.asarray(rollout["raw_covariances"], dtype=float),
        raw_cov_trace=np.asarray(rollout["raw_cov_trace"], dtype=float),
        position_error=np.asarray(rollout["position_error"], dtype=float),
        agent_classes=np.asarray(rollout["agent_classes"]),
        dcp_quantile_history=dcp.quantile_history,
        dcp_final_quantiles=dcp.final_quantiles,
        dcp_local_quantiles=dcp.local_quantiles,
        dcp_sample_counts=dcp.sample_counts,
    )


def run(args: argparse.Namespace) -> None:
    # End-to-end pipeline: rollout -> calibration scores -> DCP -> plots/metrics.
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    configure_matplotlib(output_dir)

    rollout = simulate_class_conditional_gs_ci_rollout(
        num_steps=args.steps,
        seed=args.seed,
        initial_jitter_std=args.initial_jitter_std,
        class_quantiles=default_class_quantiles(),
        dt=args.dt,
        observ_prob=args.observ_prob,
        comm_prob=args.comm_prob,
        ci_coeff=args.ci_coeff,
    )

    scores_by_agent, alpha_by_class = load_dcp_calibration_scores(
        dataset_path=args.calibration_dataset.resolve(),
        agent_classes=list(rollout["agent_classes"]),
    )
    dcp = run_distributed_classwise_dcp(
        scores_by_agent=scores_by_agent,
        agent_classes=list(rollout["agent_classes"]),
        alpha_by_class=alpha_by_class,
        num_steps=args.dcp_steps,
        step_size=args.dcp_step_size,
    )

    save_top_down_uncertainty_plot(
        rollout=rollout,
        dcp=dcp,
        output_path=output_dir / "cooperative_localization_uncertainty_tubes.png",
        tube_alpha=args.tube_alpha,
    )
    save_dcp_quantile_history_plot(
        dcp=dcp,
        agent_classes=list(rollout["agent_classes"]),
        output_path=output_dir / "dcp_quantiles_over_time.png",
    )
    save_metrics(
        output_path=output_dir / "cooperative_localization_dcp_metrics.npz",
        rollout=rollout,
        dcp=dcp,
    )


def main() -> None:
    # CLI entrypoint.
    args = parse_args()
    run(args)


if __name__ == "__main__":
    main()
